### ISSUE TITLE
Move _config.yml important bits at top

### ISSUE THREAD

**Issue by mhulse** [mhulse/jekyll-boiler#9]
Like:

``` yml
title: "Jekyll Boiler"
description: "Bare bones Jekyll example site using GitHub’s “pages” gem."
baseurl: "/election-2014-general"
keywords: ["jekyll", "test", "boiler", "github", "pages"]
paginate: 20

defaults:
```
